export 'package:flutter/material.dart';
export 'package:calculator/screens/home.dart';
export 'package:calculator/utils/themes.dart';
export '../utils/colors.dart';
export '../widgets/genderCard.dart';
export '../widgets/primary_card.dart';
export '../widgets/rounded_icon_button.dart';
export 'package:calculator/screens/result.dart';
export '../helpers/bmi_helper.dart';
